backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: "portfolio"
    label: "Portfolio"
    folder: "content/portfolio"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Featured Image", name: "thumbnail", widget: image }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "pages"
    label: "Pages"
    create: false
    files:
      - file: "content/pages/o-mnie.md"
        label: "O mnie"
        name: "about"
        fields:
          - {label: "Title", name: "title", widget: string}
          - {label: "Thumbnail", name: "thumbnail", widget: image}
          - {label: "Intro", name: "intro", widget: string}
          - {label: "Body", name: "body", widget: "markdown"}